# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patmos',
            old_name='avgadatum',
            new_name='uttrade',
        ),
        migrations.RemoveField(
            model_name='patmos',
            name='fodelsedatum',
        ),
    ]
