# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patregister', '0002_auto_20180313_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patmos',
            old_name='gift',
            new_name='gift_med',
        ),
    ]
